# Configure dockerfile.erb according to your need.

FROM <%= @image %>
MAINTAINER <%= @maintainer %> <<%= @email %>>
<% for @cmd in @build_cmd %>
  RUN <%= @cmd %>
<% end %>

<% if @entry_point %>
ENTRYPOINT <%= @entry_point %>
<% end %>
